Task 90430
AlexeiZhurov/EBSPostServices pull request #11
Opened 2022-07-18 10:40 UTC by AlexeiZhurov

2022-07-18 16:27 UTC, MadridianFox commented on app/Console/Commands/ResetPostVoice.php
> +        $post_id = $this->argument('post_id');
Переменные принято писать в camelCase, а не в snake_case

2022-07-18 16:27 UTC, MadridianFox commented on app/Console/Commands/ResetPostVoice.php
> +        if($post_id){
Не хватает пробела

2022-07-18 16:41 UTC, MadridianFox commented on app/Domain/Posts/Action/CreatedPostVoicesAction.php
>  class CreatedPostVoicesAction
Нехорошо хардкодить создание объекта action, это в будущем помешает правильно писать тесты.
Лучше передавать объект action в конструктор, чтобы потом можно было прокинуть его через сервис-контейнер

2022-07-18 16:44 UTC, MadridianFox commented on app/Domain/Posts/Action/DeletedAllVoicesPostAction.php
>          (new UpdateTotalRatingAction())->execute($id); //Вызов экшена который обновить суммарный рейтинг поста
Аналогично. Когда тебе надо написать new, стоит дважды подумать. Часто правильнее будет использовать autowiring.
Я не буду писать об этом в каждом файле, то что я в других экшенах не пишу про это, не значит что там не нужно ничего менять.

2022-07-18 16:45 UTC, MadridianFox commented on app/Domain/Posts/Action/DeletedVoicePostAction.php
>          Voice::where('post_id', $post_id)->where('id', $voice_id)->delete();
Ещё раз напоминаю, что переменные пишутся в camelCase

2022-07-18 16:51 UTC, MadridianFox commented on app/Domain/Posts/Action/PatchVoicePostAction.php
>          $voice = Voice::where('post_id', $post_id)->where('id', $voice_id);
В этом экшене неправильный код. Совсем.
Он не работает и он непонятный.
`$voice = Voice::where('post_id', $post_id)->where('id', $voice_id);` возвращает объект запроса, но ты почему-то дальше работаешь с переменной `$voice` как будто бы это объект модели.

Последовательность действий тоже неверная - ты сначала присваиваешь полю якобы модели значение,
потом вызываешь UpdateTotalRatingAction, и только после этого вызываешь сохранение модели.
Т.е. ты вызываешь пересчёт рейтинга, который берёт данные из БД, но делаешь это до сохранения изменений в БД

2022-07-18 16:52 UTC, MadridianFox commented on app/Domain/Posts/Action/UpdateTotalRatingAction.php
>          $dis_voices = $post->voices()->where('voices', '-1')->count(); //Получает отрицательный голоса
`1` и `-1` это числа, не нужно заключать их в кавычки

2022-07-18 16:54 UTC, MadridianFox commented on app/Domain/Posts/Action/UpdateTotalRatingAction.php
>          $pos_voices = $post->voices()->where('voices', '1')->count(); //Положительные
Вместо подсчёта количества голосов ты можешь просто посчитать сумму.
Это будет один запрос вместо двух.

2022-07-18 16:56 UTC, MadridianFox commented on app/Domain/Posts/Models/Post.php
> + */
Релейшен тоже нужно прописывать в докблок.
Это не просто документация, это ещё и подсказки для редактора кода, которые облегчают написание кода.

2022-07-18 16:59 UTC, MadridianFox commented on app/Domain/Posts/Models/Post.php
> + * Class Post
Вот Class Post уже лишнее. Эта надпись ничего не объясняет, не облегчает написание кода. Её можно просто не писать.

2022-07-18 17:02 UTC, MadridianFox commented on app/Http/ApiV1/Controllers/PostController.php
> +        $post = (new PatchPostAction())->execute($id, $request->all());
Выше ты уже использовал autowiring для того чтобы создать action просто указав его как аргумент метода в контроллере.
Тут нужно так же.

2022-07-18 17:11 UTC, MadridianFox commented on app/Http/ApiV1/Queries/SearchPostQuerie.php
>                  case 'rating_lte':
`$query = Post::query()->where('id', '>', 0);` вот это я не понимаю зачем ты сделал.
Расскажешь?

2022-07-18 17:16 UTC, MadridianFox commented on app/Http/ApiV1/Requests/SearchPostsRequest.php
ты пишешь
```
'filter.reating_gte'    => ['integer', 'min:0'],
'filter.reating_lte'    => ['integer', 'min:0'],
```
однако у тебя есть отрицательные голоса и сумма голосов может быть меньше нуля,
а у тебя фильтр не позволяет вводить отрицательные числа

2022-07-18 17:16 UTC, MadridianFox commented on app/Http/ApiV1/Requests/SearchPostsRequest.php
> +            'filter.user_id'        => ['integer', 'min:0'],
при фильтрации по полю, когда надо проверить есть ли такое значение, можно использовать валидатор Rule::exists()

2022-07-18 17:19 UTC, MadridianFox commented on app/Http/ApiV1/Requests/SearchPostsRequest.php
Ниже ты делаешь `$this->get('include', ['default'])`
Не вижу смысла писать внутри массива строку `'default'`

2022-07-18 17:56 UTC, MadridianFox commented on config/openapi-client-generator.php
> +        'composer_name' => 'ensi/postservices',
название пакета должно отражать его суть
было написано backend-service-skeleton-**client**
ты убрал окончание client и добавил множественное число. Теперь непонятно что это за пакет

2022-07-18 17:57 UTC, MadridianFox commented on config/openapi-clients.php
> +         'base_uri' => env('CUSTOMER_AUTH_SERVICE_HOST') . "/api/v1",
У тебя нет этих сервисов, зачем ты оставил конфиги для них?

2022-07-18 18:12 UTC, AlexeiZhurov commented on app/Http/ApiV1/Queries/SearchPostQuerie.php
>                  case 'rating_lte':
У меня баг был , если не какой where не использовался или order_by то возврощался бред

2022-07-18 18:13 UTC, AlexeiZhurov commented on app/Http/ApiV1/Requests/SearchPostsRequest.php
Так надо , это все баг с поиском

2022-07-18 18:14 UTC, AlexeiZhurov commented on config/openapi-clients.php
> +         'base_uri' => env('CUSTOMER_AUTH_SERVICE_HOST') . "/api/v1",
Я не знал что у меня есть такой конфиг вообще

2022-07-20 20:36 UTC, MadridianFox requested changes
Много замечаний

2022-07-21 20:57 UTC, MadridianFox commented on app/Http/ApiV1/Queries/SearchPostQuerie.php
>                  case 'rating_lte':
Условие 'id', '>', 0 ,бесполезно.
То как ты описал баг не объясняет зачем добавлять именно это условие.
Убери его, а если снова будешь получать бред, то найди другой способ решить проблему.

Обычно код вида `Post::query()->get()` работает нормально. Никакие бесполезные условия ему для работы не нужны.

2022-07-26 05:56 UTC, MadridianFox commented on app/Http/ApiV1/Queries/SearchPostQuerie.php
>                  case 'rating_lte':
Ок. исправлено

2022-07-26 05:58 UTC, MadridianFox commented on app/Http/ApiV1/Queries/SearchPostQuerie.php
> +                    $query->where('tags', '=', "$value");
1) не нужно переменную засовывать в строку
2) так ты не сможешь найти пост по одному тэгу

2022-07-26 05:58 UTC, MadridianFox commented on config/openapi-clients.php
> +         'base_uri' => env('CUSTOMER_AUTH_SERVICE_HOST') . "/api/v1",
Ок. Исправлено

2022-07-26 06:01 UTC, MadridianFox approved these changes

2022-07-26 08:24 UTC, merged